### ISSUE TITLE
Double clicking anywhere in a glyph's canvas causes a panic

### ISSUE THREAD

**Issue by alerque** [linebender/runebender#128]
I am currently using the latest Git build as of an hour ago, but I actually noticed this weeks ago and never got around to reporting it.

It seems that any time I double click on the glyph canvas interface I get a panic like this:

```
DEBUG [druid::localization] available locales [], current en-US
DEBUG [druid::localization] resolved: [en-US]
WARN  [druid::menu] MenuDesc::platform_default is not implemented for this platform.
INFO  [druid_shell::platform::gtk::application] gtk: Activated application
WARN  [druid::menu] MenuDesc::platform_default is not implemented for this platform.
WARN  [druid::menu] MenuDesc::platform_default is not implemented for this platform.
thread 'main' panicked at 'assertion failed: prev.button != event.button', src/mouse.rs:299:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

GTK on Linux, Xorg.

**Comment by eliheuer** [comment]
I get the same thing at commit f695676 with GTK on Linux[elementary OS 5.1.2], but not on MacOS 10.15.4.

I'm not sure if I'll be able to fix this, but I'll look into it since Desktop Linux support is something I'm interested in.

**Comment by cmyr** [comment]
this is something wonky in the GTK backend, I haven't been able to test on windows/gtk for the past few months but I can start doing that again soon. :)

**Comment by alerque** [comment]
Holler if you need any testing.

**Comment by raphlinus** [comment]
This should be fixed by https://github.com/linebender/druid/pull/1317. It hasn't landed yet but should soon.

**Comment by cmyr** [comment]
ah was wondering how to test that patch!

**Comment by alerque** [comment]
I just saw druid updates land in runebender so I rebuilt and tested this. The problem seems to have gone away, I no longer get panics clicking around on a glyph canvas.
