### ISSUE TITLE
Consider using the ttf-parser crate

### ISSUE THREAD

**Issue by RazrFalcon** [linebender/runebender#13]
[ttf-parser](https://github.com/RazrFalcon/ttf-parser) is a `font-rs` alternative (at least right now, runebender uses it only for glyph outlining). Unlike `font-rs`, `ttf-parser` has a wider set of features. Mainly the CFF support. It also a bit faster and heavily fuzzed.

**Comment by cmyr** [comment]
Cool, I'll definitely look into this when looking for ttf parsing. Our initial focus is going to be on just UFO; the current ttf stuff is really just for demo purposes I think.

**Comment by cmyr** [comment]
going to close this, we aren't going to be working with ttf in the near future.
