### ISSUE TITLE
Select tool: Mod+click outline to add off-curve points between two on-curve points

### ISSUE THREAD

**Issue by eliheuer** [linebender/runebender#130]
When using Glyphs I can hold Option+click on an outline between two on-curve points to add new off-curve points. This is useful in many different ways and used all the time while drawing.

<img width="497" alt="add-off-curve" src="https://user-images.githubusercontent.com/5162664/85622626-fb04f600-b61b-11ea-9d70-6e4b0320cd82.png">

**Comment by cmyr** [comment]
yea, definitely want to do this; the logic is in place as a result of the knife tool landing.

As a work around, you can add a point by switching to the knife tool and slicing the desired location.

**Comment by davelab6** [comment]
However, this workaround adds an oncurve point; what Eli is illustrating is the need to add (2) off curve points, to turn a straight line segment into a curve.

**Comment by cmyr** [comment]
This is implemented; alt+click with select on a line segment converts it to a curve.
