### ISSUE TITLE
Cannot type 'h' in meta data family name field

### ISSUE THREAD

**Issue by alerque** [linebender/runebender#132]
I just tried to add a name to a UFO font and discovered that I could hit "edit" and type seemingly anything I wanted in the name field except a lower case 'h'. Uppercase was fine, other letters were fine, and I could *paste* an 'h' into the field, but I couldn't type one. It just ignored me.

Linux / GTK

**Comment by cmyr** [comment]
I have.... absolutely no idea what this is about 🤯

**Comment by raphlinus** [comment]
I can replicate this, and in conversation with Colin believe it has to do with keyboard event focus processing out of order.

**Comment by cmyr** [comment]
A clue here is that 'h' is a hotkey that switches tools. 🤔

**Comment by alerque** [comment]
I bet that's a good clue. Maybe the tool hotkeys shouldn't be active while that modal is displayed. But I'm sure ya'll have a much better understanding of what's going an that I do. :stuck_out_tongue_winking_eye:

**Comment by davelab6** [comment]
This seems fixed and can be closed :)

**Comment by xorgy** [comment]
I think it might be time to reopen this, at least, I am still experiencing keyboard grab issues in text boxes. I can't type e, v, h, etc. in the Preview window text box.

**Comment by alerque** [comment]
It has never been fixed for me either. I missed the closure and think that was a mistake. As for as I know Dave isn't on Linux.
