### ISSUE TITLE
Display width and height of selection bbox

### ISSUE THREAD

**Issue by raphlinus** [linebender/runebender#145]
When more than one point is selected, display the width and height of the bbox enclosing the selection points. Among other things, this is a very useful mini-measure tool.

The second stage of this feature would be making them editable labels, and having updates to them drive a scale transformation. But I think that's much less used. I'm inclined to implement mouse-driven scaling by dragging handles associated with the selection bbox first.

**Comment by cmyr** [comment]
this is added in #150
