### ISSUE TITLE
Crash on backspace while using pen tool

### ISSUE THREAD

**Issue by futurepaul** [linebender/runebender#149]
Sorry I don't know the correct term for this state of the pen tool but here is my process to recreate:

select the pen tool

1. click to draw one point
2. click to draw second point
3. click and drag while drawing third point to pull out a curve
4. let go of click (don't click again)
5. hit backspace

I get 
```
thread 'main' panicked at 'index out of bounds: the len is 4 but the index is 4', src/draw.rs:195:30
```

**Comment by cmyr** [comment]
Thanks paul, I know there are some problems in the deletion logic but I hadn't bothered trying to track it down, so a nice reproduction is good to have!

**Comment by davelab6** [comment]
This works for me now :)
