### ISSUE TITLE
Regression on Linux

### ISSUE THREAD

**Issue by alerque** [linebender/runebender#160]
Seeing updates merged in #155 I rebuilt and tried to run on Linux.

I fired up a UFO (one that I'd just tested with the other day and was still in my command history) and double clicked on glyph. ***PANIC***.

```
thread 'main' panicked at 'index out of bounds: the len is 16 but the index is 16', src/draw.rs:206:30
```

Opening it back up and trying a few more, it seems about half of the glyphs in this particular file cause panics if I try to open them, the other half are okay. It would be a strange coincidence if testing the other day I managed not to land on any of the crashy glyphs.

**Comment by cmyr** [comment]
thanks, I'll take a look now :)

**Comment by cmyr** [comment]
@alerque any chance you can send me the UFO file? or any of the `.glif` that are crashing?

**Comment by alerque** [comment]
Sure. I was testing using [Raleway](https://github.com/theleagueof/raleway) sources at the current `master` branch, specifically I happened to open [Raleway-BlackItalic.ufo](https://github.com/theleagueof/raleway/tree/master/sources/Raleway-BlackItalic.ufo). As examples `J` and `O` (and all derivatives) cause panics reliably for me.

**Comment by raphlinus** [comment]
This might be the check for coordinate frac == 0.0, which is too strict.

**Comment by cmyr** [comment]
I would be very curious to know if this *was* working previously?

I think this is related to how UFO handles open paths; essentially there are no 'moveTo' points; in a closed path the first point is an implicit moveTo, whereas in an open path the points are to be treated as a circular buffer, with no designated start point.

When we 'close' a path, we rotate the points, which has the effect of guaranteeing that if the first segment had been a bezier, it will begin with an off-curve point.

The data in your font doesn't follow this convention; the first segment is a bezier, but it begins with the on-curve. This confused our logic, and we panic expecting there to be an extra point on the end of the path.

In any case, I'm confused as to what caused this to surface now. it *does* reflect an error in our implementation, and maybe an error in our assumptions, but it looks like that error is long-standing. 😕

**Comment by raphlinus** [comment]
FWIW, the [ufo spec](https://unifiedfontobject.org/versions/ufo3/glyphs/glif/) states "The actual list of points can be rotated arbitrarily", so we should probably deal with that on load. I think for our own internal data model, we can have the invariant that the "first" point (which is the last when the path is closed) is on-curve. (Note that if we ever deal with quadratics, outlines with no on-curve points are possible)

**Comment by raphlinus** [comment]
I'll note, the frac check causes panics when loading Inconsolata, so there are two problems here :)
