### ISSUE TITLE
Glyph preview sometimes has wierd rendering

### ISSUE THREAD

**Issue by alerque** [linebender/runebender#177]
I just tried to have a look at the sources for [Ostrich Sans Inline Italic](https://github.com/theleagueof/ostrich-sans/tree/fontship-overhaul/sources/OstrichSans-InlineItalic.ufo) and noticed several glyphs look different in the preview that the actual shapes warrant:

![image](https://user-images.githubusercontent.com/173595/98045836-25708680-1e3a-11eb-8546-190cf66c56eb.png)

**Comment by alerque** [comment]
(And Sorry about the screenshot having a mismatch between Ⓒ and Ⓡ, but they are both messed up the same way.)

**Comment by cmyr** [comment]
Cool, thanks, will investigate. :)

**Comment by alerque** [comment]
This looks great in the latest build!
