### ISSUE TITLE
Save deletes UFO source

### ISSUE THREAD

**Issue by alerque** [linebender/runebender#178]
Working with the [same source](https://github.com/theleagueof/ostrich-sans/tree/fontship-overhaul/sources/OstrichSans-InlineItalic.ufo?rgh-link-date=2020-11-03T22%3A09%3A38Z) as #177, hitting File→Save has the (unexpected) effect of deleting the UFO sources entirely. The console messages imply something else:

```
INFO  [runebender::data] saving to "sources/OstrichSans-InlineItalic.ufo/"
ERROR [runebender::app_delegate] saving failed: 'To prevent data loss, norad will not save files created elsewhere.'
```

If you can't save that's fine, but nuking files while claiming to prevent data-loss is a bad look ;-)

**Comment by cmyr** [comment]
Oohhh.. we aren't deleting it, we're just... carefully backing it up. There should be a folder `XXX_backups` in the same location as the original ufo, and it should contain the untouched sources; `XXX` should be the name of the opened file, without the extension. If this is *not* the case I'm extremely confused.

In any case we should definitely be doing our 'not created here' check before we do that backing up, though. 😅

**Comment by alerque** [comment]
Okay yes the backups do exist. I wasn't seeing them because of a gitignore rule.

But this is **not** how it should work. Having a backups *in case* something goes wrong is one thing (e.g. a panic mid-operation). If you *know* it's going to go wrong before you even start, deleting the user's content is the wrong move.

**Comment by cmyr** [comment]
Agree, it's very counterintuitive. The goal here was to be maximally defensive about *not* corrupting the user's content, but hiding it somewhere undocumented is not much better.

I think the general approach to atomic saving here is a bit poor in any case; instead of moving the old data and then writing directly to the target path, we should write to a temporary path, then move the old data before moving from the temporary path to the target path.

**Comment by alerque** [comment]
> instead of moving the old data and then writing directly to the target path, we should write to a temporary path, then move the old data before moving from the temporary path to the target path

I don't think that's the only maximally defensive way, and it certainly causes problems for a number of other uses. When you move files and create new ones in their place, you loose all the file system tracking data like inode numbers. This actually introduces *more* chances for corruption, not less. It also throws off any other tooling. For example one thing I do routinely is use ionofify signals from the file system to watch files & directories and trigger things (builds, preview updates, etc.) when they change. By moving the current source to a backup and creating a new one you blow any tooling that even tries to go down that road out of the water. Timestames also get lost, and many modern file systems (especially ones optimized for solid state memory that do their own COW) get hamstrung.

If you must make backups, at least **copy** from the source to the backup, then rewrite the source files in place.

Additionally an option to completely disable backup shenanigans would be much appreciated. My projects are both tracked in Git and stored on COW file systems with snapshotting.

**Comment by cmyr** [comment]
Good notes, I'll keep all of that in mind. The save stuff is all very much half-baked, and the rationale for the current state is that I want to avoid losing data at all costs, but it definitely won't be a long-term solution.
