### ISSUE TITLE
No pan functionality (Linux GTK)

### ISSUE THREAD

**Issue by alerque** [linebender/runebender#190]
Linux / GTK build on X11.

I can scroll the viewport using mouse wheels (both vertical and horizontal), but there is no working pan function. Recently in #189 I was made aware that the preview mode should also double as a pan mode. Pressing space or hitting the preview icon does flip to a preview mode, but no pan functionality is activated. I would expect:

* Pressing space to instantly activate a pan mode where any mouse motion results in a pan motion.
* Activating the preview mode to include a click-drag action that pans instead of activating a selection rectangle.

**Comment by cmyr** [comment]
Good issue, pan is missing everywhere I believe; if I recall the preview/pan tool was added as part of doing some other work and didn't get fleshed out.
