### ISSUE TITLE
can't compile druid-shell

### ISSUE THREAD

**Issue by EwonRael** [linebender/runebender#196]
Hey,

I'm not very good with the techy stuff. I can't seem to compile the latest version because it's failing to build druid-shell

`For more information about this error, try 'rustc --explain E0658'.
error: could not compile 'druid-shell'.`

Any suggestions?

**Comment by cmyr** [comment]
@EwonRael what operating system are you using? Were you able to compile earlier versions?

If there's any other information that would be useful. Some initial things to try would be making sure your version of rust is up-to-date.

**Comment by EwonRael** [comment]
yes sorry I updated rust and now everything works fine. I feel silly but at least it was an easy fix

**Comment by cmyr** [comment]
No need to feel silly, and happy you've got it working!
