### ISSUE TITLE
Support opening metainfo.plist on Windows

### ISSUE THREAD

**Issue by madig** [linebender/runebender#21]
The Windows file picker can't "open" a .ufo as a file. Font editors on Windows commonly do "UFO package (*.ufo|metainfo.plist)" and then you click the metainfo.plist file. Note that you need to do path manipulation to toss metainfoplist out again to get the true UFO path.

**Comment by cmyr** [comment]
Okay, good suggestion. I was thinking about setting the "allow opening of directories" bit in windows, but your idea might make more sense.
