### ISSUE TITLE
Where to install theme file (and that you have to) is not documented

### ISSUE THREAD

**Issue by alerque** [linebender/runebender#215]
For the last few weeks I've been unable to run Runebender when installed from the (Git HEAD tracking) system package I usually run it from.

```
ERROR [druid_theme_loader::widget] error loading theme file: io error loading theme: 'No such file or directory (os error 2)'
thread 'main' panicked at 'Missing key: 'runebender.primary-text-color'', /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid/src/env.rs:245:25
```

It does run from `cargo run` or directly from the target directory in the source, so I assume this is an issue with not packaging the theme file in a place the system installed binary can find it. The trouble is I don't see any documentation on where I should put that file.

It's probably worth noting that `cargo install` doesn't place the necessary resources anywhere either. This may not be fixable on this project's side. I'm well aware that `cargo` is not really suited for use as a general purpose make/install system — at some point a wrapper of some kind (GNU Make, Cmake, Meson, etc.) might be in order. For now lets start with: **where does the theme file need to be?**

It seems like it's looking in `resources/` relative to `$CWD`. This is untenable because `$CWD` will almost never have any relation to the binary.

**Comment by cmyr** [comment]
ugh sorry to have missed this. Currently I always expect runebender to be run from the source directory; and the theme is included in `runebender/resources`. Before we do platform packaging we will need a solution to locating resource files; there's an open issue for this in druid.

In the meantime, if you are running runebender from another location, maybe we could provide an environment variable to set the theme file?

**Comment by alerque** [comment]
How about detecting an env variable in `build.rs` such that the base path to the shared assets folder could be baked in ready to run from the system location without needing to mess with the run time environment? For many *nix systems this is going to be `/usr/share/runebender` or similar. Most build and packaging systems have something like a configure flag for telling compiled binaries where they should look for things. A fallback to looking in the current directory would cover the case where it is run from the source directory.
