### ISSUE TITLE
Text preview window panics on Linux

### ISSUE THREAD

**Issue by alerque** [linebender/runebender#231]
I just tried the new text preview window from #223 on Linux, and it panics the moment I click on the menu item:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', runebender-lib/src/virtual_font.rs:165:18
```

**Comment by cmyr** [comment]
Oops, thanks! This was just general sloppiness, it would crash anytime the font didn't contain the the '.notdef' glyph.
