### ISSUE TITLE
Compiler error: failed to run custom build command for `cairo-sys-rs v0.7.0`

### ISSUE THREAD

**Issue by eliheuer** [linebender/runebender#4]
At commit a001e77 on macOS running `cargo run --bin ufo_editor ~/Desktop/MutatorSansBoldWide.ufo` gives me the following error: 
`failed to run custom build command for 'cairo-sys-rs v0.7.0'`

This was fixed by running: `export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig" cargo build`

How can this error be prevented from occurring?

**Comment by cmyr** [comment]
I believe this is a problem with the cairo-sys-rs crate. I've failed an issue there: https://github.com/gtk-rs/cairo/issues/263

**Comment by bghryct** [comment]
building RuneBender for the first time and ran into the same issue.

**Comment by raphlinus** [comment]
Closing this as it seems to be specific to Cairo on macOS, which is no longer needed, as we draw using Core Graphics.
