### ISSUE TITLE
measurement tool

### ISSUE THREAD

**Issue by cmyr** [linebender/runebender#45]
One of the primary tools in a font editor.

**Comment by raphlinus** [comment]
Yes, I've given some thought to this. It's a juicy problem, involving nontrivial (but not extraordinarily difficult) numerical code at the curve level. I'd like to take it on, but am aware of blocking progress if I'm not able to schedule the work soon.

**Comment by madig** [comment]
I think the numerical code in TruFont Qt/WX can serve as an inspiration. I think I had a look at the code in WX.

**Comment by raphlinus** [comment]
There's a basic measurement tool in place now, so closing. There are of course always more improvements that can be made.
