### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by eliheuer** [linebender/runebender#6]
Currently, styling decisions are hardcoded, but there has been some discussion about using TOML files for setting values relating to colors, lines, fonts, margins, etc. This way, the theme used for the UI can be changed easily, and users who are comfortable building from source can make custom themes. 

I think it makes sense to do this sooner rather than later so that replacing hardcoded styling decisions doesn't become a difficult task.

The initial themes could just be a light and dark theme.

**Comment by eliheuer** [comment]
Small update on this. I have a branch in my fork now where I keep my personal dark mode theme: https://github.com/eliheuer/runebender/tree/dark-mode

To get this I needed to change constants in three files:
```
src/draw.rs
src/theme.rs
src/widgets/editor.rs
```
Maybe the constants for style and visual appearance can all be moved to `src/theme.rs`? I still think it would be nice to have a few different themes to choose from and an easy way for people with beginner level programming skills to make and share custom themes.

![2020-06-26-155742_1920x1080_scrot](https://user-images.githubusercontent.com/5162664/85896443-786c6a00-b7c6-11ea-9aee-fd2dac95c657.png)

**Comment by cmyr** [comment]
yea, I think moving drawing related constants to theme is totally fine, and I can look into some mechanism for loading these things from disk.

**Comment by eliheuer** [comment]
@ctrlcctrlv did a nice job making a [constants.rs](https://github.com/mfeq/Qglif/blob/master/src/renderer/constants.rs) file in his [Modular Font Editor Q](https://github.com/mfeq) project. It's worth looking at for anyone who ends up working on this.

I also have a branch now that has my own take on a default theme, shown below: https://github.com/eliheuer/runebender/tree/elihs-theme

![elis-runebender-theme](https://user-images.githubusercontent.com/5162664/101301177-d6c55c00-37ec-11eb-939b-59afd79962dc.png)

**Comment by cmyr** [comment]
Going to treat this as addressed, as of #199 and #220.
