### ISSUE TITLE
State of Libre Graphics 2020

### ISSUE THREAD

**Issue by aoloe** [linebender/runebender#79]
The [Libre Graphics Meeting 2020](https://libregraphicsmeeting.org/2020/) is happening at the end of May in Rennes!

As usual, the first conference will be the State of Libre Graphics, where we will give an overview of what has happened during the last year in the world of Libre Graphics.

You're very welcome to submit two slides for your project. They will be presented by the moderator of the _State of Libre Graphics_.
Instructions for submitting the slides can be found in the Github repository that will contain all slides:

<https://github.com/libregraphicsmeeting/state-of-lg-2020>

If you have further questions, don't hesitate to [open a ticket](https://github.com/libregraphicsmeeting/state-of-lg-2020/issues) in the same repository.

And, of course, you're very welcome to [join us in Rennes](https://libregraphicsmeeting.org/2020/en/register.html)!

**Comment by aoloe** [comment]
... ps: i did not find any contact information and the #zulip channel does not seem to be active anymore...

**Comment by madig** [comment]
https://xi.zulipchat.com/#narrow/stream/197829-runebender

**Comment by aoloe** [comment]
yes, i've tried that link and got a long list of channels but not one that would be related to runebender... probably my mistake.

**Comment by cmyr** [comment]
the zulip is very active! A lot of our work this year has been more focused on the underlying libraries (druid, piet) but we are making some good progress. I will look into preparing some update slides, at the very least. :)

**Comment by aoloe** [comment]
thanks @cmyr .

as a i said: it's probably me who did misunderstand how zulip works.

**Comment by davelab6** [comment]
@cmyr were you able to contribute some slides for LGM? I wonder if LGM 2021 may happen again online, there was a poll last month but no results posted so far...

**Comment by cmyr** [comment]
I was not, this issue got lost in the march pandemic fog. 😞
