### ISSUE TITLE
Suggestion for installation hints on macOS

### ISSUE THREAD

**Issue by kud1ing** [linebender/runebender#9]
This is probably too early, but i've found that on a Mac i need to call something like

    export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/opt/libffi/lib/pkgconfig"

in order to make `runebender` compile. Otherwise i'd got

    Package libffi was not found in the pkg-config search path.

while compiling `cairo-sys-rs`.

**Comment by cmyr** [comment]
Yea, a workaround is mentioned in #4. If you would like to update the README to include these instructions, I'd be happy to accept a PR!

**Comment by kud1ing** [comment]
Ah, closing this as duplicate then.
